export const PLATFORM_YOUTUBE_STREAM = 1;
export const PLATFORM_YOUTUBE_MOVIE = 2;
export const PLATFORM_YOUTUBE_SHORT = 3;
export const PLATFORM_NICONICO_PETIT_LOVE_STREAM = 4;
export const PLATFORM_NICONICO_BIG_LOVE_STREAM = 5;
export const PLATFORM_NICONICO_BIG_LOVE_MOVIE = 6;
